version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build: .
    volumes:
      - .:/shipment-api
    ports:
      - "8001:8001"
    image: app:shipment-api
    container_name: shipment-api_container
    depends_on:
      - db
    tty: true
    stdin_open: true    
    command: python manage.py runserver 0.0.0.0:8001